
from app import app, db
from models import Product

with app.app_context():

    Product.query.delete()
    product1 = Product(product_name = "Fresh Woodlands Soap", category = 'Soap', description= 'Rich, earthy and herbaceous, the scent of our Fresh Woodlands soap bar is one that both men and women can appreciate.  Fresh Woodlands is a completely vegan, animal and eco-friendly soap bar containing no synthetics or petroleum. It is handcrafted in small batches in the USA, using the old-fashioned cold process method. FLO+THEO soap bars provide a rich creamy lather and are made with luxurious oils and butters, herbs, glycerin (a natural humectant), natural mineral pigments and 100% pure essential oils.', directions ='Rub the soap directly onto a wash cloth or loofah and get a really good lather, then apply to wet skin. Use a clean cloth every time you wash, and wash your loofah under clean water after each use', image_url = 'https://images.squarespace-cdn.com/content/v1/52594417e4b030e5f06cf43c/1383223537639-NGJFBOKH8D0JZWVPAUT4/Fire_Soap.jpg?format=750w', unit_price=10)

    product2 = Product(product_name = "Lavender Flower Soap", category = 'Soap', description= 'The aroma of our Lavender Flower soap bar is reminiscent of a bright bouquet of fresh, flowering lavender with a sweet and delicate finish. Lavender Flower is a completely vegan, animal and eco-friendly soap bar containing no synthetics or petroleum. It is handcrafted in small batches in the USA, using the old-fashioned cold process method. FLO+THEO soap bars provide a rich creamy lather and are made with luxurious oils and butters, herbs, glycerin (a natural humectant), natural mineral pigments and 100% pure essential oils.', directions ='Rub the soap directly onto a wash cloth or loofah and get a really good lather, then apply to wet skin. Use a clean cloth every time you wash, and wash your loofah under clean water after each use', image_url = 'https://images.squarespace-cdn.com/content/v1/52594417e4b030e5f06cf43c/1383223562958-DZ77DNBEYAMRULUJ52IA/Lavender_Soap.jpg?format=500w', unit_price=10)

    product3 = Product(product_name = "Orange Harvest Soap", category = 'Soap', description= 'Our Orange Harvest soap bar is a crisp and clean blend. It will have you feeling, like you are walking through a grove of citrus trees on a beautiful, sunny Sunday morning. It is completely vegan, animal and eco-friendly and contains no synthetics or petroleum. It is handcrafted in small batches in the USA, using the old-fashioned cold process method. FLO+THEO soap bars provide a rich creamy lather and are made with luxurious oils and butters, herbs, glycerin (a natural humectant), natural mineral pigments and 100% pure essential oils.', directions ='Rub the soap directly onto a wash cloth or loofah and get a really good lather, then apply to wet skin. Use a clean cloth every time you wash, and wash your loofah under clean water after each use', image_url = 'https://images.squarespace-cdn.com/content/v1/52594417e4b030e5f06cf43c/1383223585363-JFPAQVQQB1E5SYWYPJXV/Orange_Soap.jpg?format=500w', unit_price=10)

    product4 = Product(product_name = "Lemon Orchard Soap", category = 'Soap', description= 'Lather up with our Lemon Orchard soap bar. This soap bar has an aroma best described as a light, lemony romantic scent with herbal undertones.  Lemon Orchard is a completely vegan, animal and eco-friendly soap bar, containing no synthetics or petroleum. It is handcrafted in small batches in the USA, using the old-fashioned cold process method. FLO+THEO soap bars provide a rich creamy lather and are made with luxurious oils and butters, herbs, glycerin (a natural humectant), natural mineral pigments and 100% pure essential oils.', directions ='Rub the soap directly onto a wash cloth or loofah and get a really good lather, then apply to wet skin. Use a clean cloth every time you wash, and wash your loofah under clean water after each use', image_url = 'https://images.squarespace-cdn.com/content/v1/52594417e4b030e5f06cf43c/1383223671745-RODOMY4W444PL68WZ58E/Mint_Soap.jpg?format=500w', unit_price=10)

    product5 = Product(product_name = "Wild Mint Soap", category = 'Soap', description= 'Whoa Nelly! This is often the initial reaction from customers when they experience the scent of our Wild Mint for the first time. The minty and herbal aroma notes of Wild Mint is certainly guaranteed to wake you up in the morning and will leave you feeling refreshed and revitalized. Wild Mint is a completely vegan, animal and eco-friendly soap bar, containing no synthetics or petroleum. It is handcrafted in small batches in the USA, using the old-fashioned cold process method. FLO+THEO soap bars provide a rich creamy lather and are made with luxurious oils and butters, herbs, glycerin (a natural humectant), natural mineral pigments and 100% pure essential oils.',directions ='Rub the soap directly onto a wash cloth or loofah and get a really good lather, then apply to wet skin. Use a clean cloth every time you wash, and wash your loofah under clean water after each use', image_url = 'https://images.squarespace-cdn.com/content/v1/52594417e4b030e5f06cf43c/1383223649198-E3AI7T9UWN2Q9UVI4LVO/Lemon_Soap.jpg?format=500w', unit_price=10)

    product6 = Product(product_name = "Activated Charcoal Soap", category = 'Soap', description= 'The key ingredient in this unscented black soap bar is activated charcoal.  Activated charcoal is known for its superb absorption powers and for its ability to draw out oil, dirt and other substances from clogged pores. Activated Charcoal is a completely vegan, animal and eco-friendly soap bar containing no synthetics or petroleum. It is handcrafted in small batches in the USA, using the old-fashioned cold process method. ', directions ='Rub the soap directly onto a wash cloth or loofah and get a really good lather, then apply to wet skin. Use a clean cloth every time you wash, and wash your loofah under clean water after each use', image_url = 'https://images.squarespace-cdn.com/content/v1/52594417e4b030e5f06cf43c/1427166993792-AV6LQ2ZNZ0XKNBPG7KIY/CharcoalSoap.jpg?format=500w', unit_price=10)

    product7 = Product(product_name = "Lavender Flower Body Butter", category = 'Body Butter',
    description= 'Lavender Flower Body Butter is a deliciously, creamy natural moisturizer. This whipped to perfection body butter is highly concentrated with the finest ingredients, nature has to offer (meaning a little goes a very long way).  Cocoa Butter and Shea Butter, our key ingredients are naturally rich in Vitamins A, E, and F, ensuring glowing and healthy skin. The aroma of our Lavender Flower is reminiscent of a bright bouquet of fresh, flowering lavender with a sweet and delicate finish. This handmade, velvety soft body butter melts into your skin on contact, allowing for a truly luxurious experience.',
    directions ='Apply a generous scoop of body butter directly to your skin and gently massage into skin using firm, broad strokes until full absorbed', image_url = 'https://images.squarespace-cdn.com/content/v1/52594417e4b030e5f06cf43c/1383064238252-ADGOHKIS6NTS9JMVCKN6/Lavender_butter_3.png?format=1000w', unit_price=28)

    product8 = Product(product_name = "Lemon Orchard Body Butter", category = 'Body Butter',
    description= 'Our Lemon Orchard handmade, whipped body butter is all you need to hydrate dry and thirsty skin. Ingredients such as Cocoa Butter, Shea Butter and Coconut Oil are filled with vitamins A, E, F and fatty acids, nourishing and protecting the skin. ',
    directions ='Apply a generous scoop of body butter directly to your skin and gently massage into skin using firm, broad strokes until full absorbed', image_url = 'https://images.squarespace-cdn.com/content/v1/52594417e4b030e5f06cf43c/1383064298915-GK3JWZQP88FP8X76NB4L/Lemon_butter_3.png?format=1000w', unit_price=28)

    product9 = Product(product_name = "Orange Harvest Body Butter", category = 'Body Butter',
    description= 'Orange Harvest Body Butter is a simple yet effective blend of Cocoa Butter, Shea Butter , Coconut, Oil and Essential oils. The body butter is filled with active anti-oxidants, vitamins and nutrients that will ensure your skin remains super moisturized and hydrated. This blend is light, it quickly absorbs into the skin and is packed with the very best ingredients to keep skin healthy and glowing. Orange Harvest is a crisp and clean blend. This intoxicating aroma evokes feelings of walking through a grove of citrus trees on a beautiful sunny Sunday morning. Smooth, silky skin never felt this good.',
    directions ='Apply a generous scoop of body butter directly to your skin and gently massage into skin using firm, broad strokes until full absorbed', image_url = 'https://images.squarespace-cdn.com/content/v1/52594417e4b030e5f06cf43c/1383064328273-4YSQIM4DUZT4TSAT00VL/Orange_butter_3.png?format=1000w', unit_price=28)

    product10 = Product(product_name = "Wild Mint Body Butter", category = 'Body Butter',
    description= 'Rich, aromatic, vegan and 100% natural, Wild Mint Body Butter has a lot of moisturizing power. The blend of Cocoa Butter, Shea Butter and Coconut Oil, means that this mixture is bursting with vitamins, minerals and antioxidants. It is very emollient, easily absorbs into the skin, leaving it incredibly soft and hydrated.The minty and herbal aroma notes of Wild Mint are certain to make you feel refreshed and revitalized. Your skin will feel the difference.',
    directions ='Apply a generous scoop of body butter directly to your skin and gently massage into skin using firm, broad strokes until full absorbed', image_url = 'https://images.squarespace-cdn.com/content/v1/52594417e4b030e5f06cf43c/1383064362956-D3OMUI518AMPH39H9EV5/Mint_butter_3.png?format=1000w', unit_price=28)

    product11 = Product(product_name = "Orange Harvest Body Oil", category = 'Body Oil',
    description= 'Handcrafted using only the highest quality natural oils, Orange Harvest body oil is naturally rich in vitamins and antioxidants that feed the skin.  This light blend is extremely moisturizing yet highly absorbent, meaning it won’t leave your skin feeling heavy or greasy.. Orange Harvest is a crisp and clean scent. This intoxicating aroma evokes feelings of walking through a grove of citrus trees on a beautiful sunny Sunday morning.FLO+THEO body oils are multi-purpose, use as a daily moisturizer, a massage oil or/and as a scalp treatment.',
    directions ='Apply body oil straight out of the shower while the skin is still damp', image_url = 'https://images.squarespace-cdn.com/content/v1/52594417e4b030e5f06cf43c/1427155670214-H8RSCHJ6PK0DKUDSQ9CI/2015_03_15_15924.jpg?format=750w', unit_price=24)

    product12 = Product(product_name = "Lavender Flower Body Oil", category = 'Body Oil',
    description= 'Nourish and condition even the most sensitive skin, with our all-natural Lavender Flower body oil.  A blend of sweet almond oil, coconut oil, vitamin e and essentials oils, this formulation easily absorbs in the skin whilst also being deeply hydrating and nourishing.  The aroma of our Lavender Flower is reminiscent of a bright bouquet of fresh, flowering lavender with a sweet and delicate finish. FLO+THEO body oils are multi-purpose, use as a daily moisturizer, massage oil and/or as a scalp treatment.',
    directions ='Apply body oil straight out of the shower while the skin is still damp', image_url = 'https://images.squarespace-cdn.com/content/v1/52594417e4b030e5f06cf43c/1426814170259-QQKUK4HN9H1ZSNB39J0V/lavender_oil.jpg?format=750w', unit_price=24)

    product13 = Product(product_name = "Wild Mint Body Oil", category = 'Body Oil',
    description= 'Formulated with all-natural nourishing oils, Wild Mint body oil is an ideal moisturizer suitable for all skin types. This highly absorbent blend provides vitamins, antioxidants, fatty acids and moisture to the skin. The minty and herbal aroma notes of the Wild Mint scent is certain to make you feel refreshed and revitalized. FLO+THEO body oils are multi-purpose, use as a daily moisturizer, massage oil and/or as a scalp treatment. The minty and herbal aroma notes of Wild Mint are certain to make you feel refreshed and revitalized.',
    directions ='Apply body oil straight out of the shower while the skin is still damp', image_url = 'https://images.squarespace-cdn.com/content/v1/52594417e4b030e5f06cf43c/1426814201625-AN2ORQI5QFP7QZ190016/mint_oil.jpg?format=750w', unit_price=24)

    product14 = Product(product_name = "Beard Elixir", category = 'Men',
    description= "FLO+THEO's Beard Elixir naturally hydrates the skin whilst adding moisture and shine to the beard and mustache. Made with high quality natural plant derived oils and Vitamin E, our elixir is highly concentrated meaning only a few drops are need to soften and tame facial hair.  ",
    directions ='Apply sparingly to palms and rub into beard for best results.', image_url = 'https://images.squarespace-cdn.com/content/v1/52594417e4b030e5f06cf43c/1415936316772-NVLONRJ6KD7LYFEP6WNH/beard_width.png?format=300w', unit_price=20)

    product15 = Product(product_name = "Beard Elixir and Activated Charcoal Soap", category = 'Men',
    description= 'The perfect manly grooming combo.  Groom yourself with this Beard Elixir and Activated Charcoal Soap Kit, the elixir naturally adds shine and moisture to the beard whilst the soap bar draws out dirt and oil from clogged pores.',
    directions ='Apply body oil straight out of the shower while the skin is still damp', image_url = 'https://images.squarespace-cdn.com/content/v1/52594417e4b030e5f06cf43c/1433258907651-EFCO4D0F4NGBKI9ET7EX/2015_03_16_15931.jpg?format=500w', unit_price=28)










    products = [product1, product2, product3, product4,product5,product6, product6, product7, product8, product9, product10,product11, product12, product13, product14, product15]

    db.session.add_all(products)
    db.session.commit()
